services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ko-proj-api
    expose:
      - "8080"

  portal:
    build:
      context: ./portal/plane-manager
      dockerfile: Dockerfile
    container_name: ko-proj-portal
    ports:
      - "8081:80"
    depends_on:
      - api
